language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
  - echo $DEPLOY_HOST_KEY >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_573f30465fed_key -iv $encrypted_573f30465fed_iv
    -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - npm test
  - npm run build
before_deploy:
  - npm prune --production
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -av -e ssh --exclude='.git/' --exclude='src/' --filter='protect .well-known' --filter='protect .env' ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    on:
      branch: master
